### PR TITLE
Defers loading @iopipe/core until dependency cycles resolve

### LINKED ISSUE #45: Errors silently on local invoke
Attempted local invocations via `sls invoke local` and did not get profiling info in HUD.

Worked fine when running the function on AWS.

### LINKED ISSUE #64: Enabling profiling via env variable in Serverless Framework not working
When settings `IOPIPE_ENABLE_PROFILER: true` in serverless.yml file profiling is not getting enabled and I get an error in my CW logs with debug on

Node10
serverless-iopipe-layers: 0.3.3
arn:aws:lambda:us-east-1:146318645305:layer:IOpipeNodeJS10:1

```
2019-07-09T16:09:30.606Z    8013aca9-2f0e-4702-9aee-6954d5edc30a    ERROR    TypeError: Cannot read property 'getFileUploadMeta' of undefined
 at ProfilerPlugin.getFileUploadMeta (/opt/nodejs/node_modules/@iopipe/profiler/dist/index.js:124:23)
 at ProfilerPlugin.preInvoke (/opt/nodejs/node_modules/@iopipe/profiler/dist/index.js:96:28)
 at /opt/nodejs/node_modules/@iopipe/core/dist/iopipe.js:1984:30
 at Array.map (<anonymous>)
 at IOpipeWrapperClass._callee3$ (/opt/nodejs/node_modules/@iopipe/core/dist/iopipe.js:1980:44)
 at tryCatch (/opt/nodejs/node_modules/@iopipe/core/dist/iopipe.js:2244:40)
 at Generator.invoke [as _invoke] (/opt/nodejs/node_modules/@iopipe/core/dist/iopipe.js:2478:22)
 at Generator.prototype.(anonymous function) [as next] (/opt/nodejs/node_modules/@iopipe/core/dist/iopipe.js:2296:21)
 at step (/opt/nodejs/node_modules/@iopipe/core/dist/iopipe.js:1034:30)
 at /opt/nodejs/node_modules/@iopipe/core/dist/iopipe.js:1052:14
```

### PR DESCRIPTION
**Pull request by mrickard**
Waits to require core's util so that dependency loading can be completed, and makes that conditional to avoid unnecessary loading.
Moves @iopipe/core to devDependencies
Closes #45
Closes #64

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -107,7 +107,13 @@ class ProfilerPlugin {
     }
   }
 
-  getFileUploadMeta() {
+  async getFileUploadMeta() {
```
Comment (kolanos) [inline src/index.js]: Would this be better as a getter?

Comment (mrickard) [reply src/index.js]: It looks as though this is following/importing the interface to this functionality in core. Here, it would make more sense as a getter, but I also don't think there's a lot of benefit to changing this interface.
